[package]
name = "telegenic-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.telegenic]
path = ".."

[[bin]]
name = "gvcp"
path = "fuzz_targets/gvcp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "gvsp"
path = "fuzz_targets/gvsp.rs"
test = false
doc = false
bench = false

[[bin]]
name = "discovery"
path = "fuzz_targets/discovery.rs"
test = false
doc = false
bench = false

[[bin]]
name = "xml_url"
path = "fuzz_targets/xml_url.rs"
test = false
doc = false
bench = false

[[bin]]
name = "unzip"
path = "fuzz_targets/unzip.rs"
test = false
doc = false
bench = false

[[bin]]
name = "genicam_xml"
path = "fuzz_targets/genicam_xml.rs"
test = false
doc = false
bench = false

[[bin]]
name = "formula"
path = "fuzz_targets/formula.rs"
test = false
doc = false
bench = false
